### PR TITLE
Add example timeline solution

### PR DESCRIPTION
**Pull request by tanyapowell**

### CODE REVIEW

**Review by Genyus — COMMENTED** [review]
@tanyapowell Did we decide in the convo with Char that we’d use a src folder for assignment resources from the JS unit going forwards?

**Comment by tanyapowell** [comment]
> @tanyapowell Did we decide in the convo with Char that we’d use a src folder for assignment resources from the JS unit going forwards?

This isn't a resource. This is just an example solution to help you create tests. Thought you asked for an example of a solution?

**Comment by Genyus** [comment]
> This isn't a resource. This is just an example solution to help you create tests. Thought you asked for an example of a solution?

Yes, it's just an example, but the structure here needs to reflect what's expected in the assignment repo so the tests are looking in the correct locations. Don't worry about it though, I'll reorganise as needed. Everything looks fine

**Review by Genyus — APPROVED** [review]
Good to go

**Pull request merged**
